# Generated by Django 5.2.1 on 2025-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('subtitle', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('INSTRUMENT', 'Instrument'), ('EFFECT', 'Effect')])),
                ('description', models.CharField(max_length=1000)),
                ('sys_req', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='products/full/')),
                ('file_demo', models.FileField(upload_to='products/demo/')),
                ('screenshot', models.ImageField(upload_to='products/screenshots/')),
            ],
        ),
    ]
