# Generated by Django 5.2.1 on 2025-05-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_license_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=150)),
                ('hero_subtitle', models.CharField(max_length=150)),
                ('hero_link', models.CharField(max_length=150)),
                ('hero_image', models.ImageField(upload_to='home/')),
                ('category_instruments_image', models.ImageField(upload_to='home/')),
                ('category_effects_image', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
